{"title": "Topic 001 Question 005", "body": ["A developer has created an AWS Lambda function that is written in Python. The Lambda function reads data from objects in Amazon S3 and writes data to an Amazon DynamoDB table. The function is successfully invoked from an S3 event notification when an object is created. However, the function fails when it attempts to write to the DynamoDB table.", "What is the MOST likely cause of this issue?"], "options": ["The Lambda function's concurrency limit has been exceeded.", "DynamoDB table requires a global secondary index (GSI) to support writes.", "The Lambda function does not have IAM permissions to write to DynamoDB.", "The DynamoDB table is not running in the same Availability Zone as the Lambda function."], "answer": "C"}